# Generated by Django 4.2.2 on 2023-06-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_chatmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
